version: 2.1
orbs:
  upx: circleci/upx@1.0.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - upx/install

      - run: ./build.sh

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - persist_to_workspace:
          root: .
          paths:
            - artifacts
            - VERSION

  deploy:
    docker:
      - image: cibuilds/github:0.13

    steps:
      - attach_workspace:
          at: .

      - run:
          name: "Publish Release"
          command: |
            VERSION="$(cat VERSION)"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
